steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/churn/preprocess:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/churn/preprocess:latest'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/churn/preprocess:latest'
  - 'train/'
images: ['gcr.io/$PROJECT_ID/churn/preprocess:latest']
